version: "3.9"

services:
  db:
    image: mariadb:10.11
    container_name: forestguardian-test-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: forestguardian_test
    ports:
      - "3306:3306"
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/001_dump.sql
    restart: "no"
